name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    # Intentionally set to an older version for better compatibility.
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            cc: gcc
            cgo: 1
            tags: ""
            suffix: ""
          - goos: linux
            goarch: amd64
            cc: gcc
            cgo: 1
            tags: "fuse3"
            suffix: "-fuse3"
          - goos: linux
            goarch: arm64
            cc: aarch64-linux-gnu-gcc
            cgo: 1
            tags: ""
            suffix: ""
          - goos: linux
            goarch: arm64
            cc: aarch64-linux-gnu-gcc
            cgo: 1
            tags: "fuse3"
            suffix: "-fuse3"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse-dev fuse3 libfuse3-dev
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: ${{ matrix.cgo }}
        CC: ${{ matrix.cc }}
      run: |
        VERSION="${{ github.ref_name }}"
        COMMIT_HASH_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
        BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        BINARY_NAME="syncmate-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        
        TAGS_FLAG=""
        if [ -n "${{ matrix.tags }}" ]; then
          TAGS_FLAG="-tags=${{ matrix.tags }}"
        fi
        
        go build -v ${TAGS_FLAG} -ldflags="-s -w \
          -X 'main.VERSION=${VERSION}' \
          -X 'main.BUILD_TIME=${BUILD_TIME}' \
          -X 'main.COMMIT_HASH=${COMMIT_HASH_SHORT}'" \
          -o "${BINARY_NAME}" .

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          syncmate-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}${{ matrix.goos == 'windows' && '.exe' || '' }}
        generate_release_notes: true
        draft: ${{ github.event_name == 'workflow_dispatch' }}
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
